/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mediatek_android_IoTManager_IoTManagerNative */

#ifndef _Included_mediatek_android_IoTManager_IoTManagerNative
#define _Included_mediatek_android_IoTManager_IoTManagerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    InitSmartConnection
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_InitSmartConnection
  (JNIEnv *, jobject);

/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    StartSmartConnection
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;B)I
 */
JNIEXPORT jint JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_StartSmartConnection
  (JNIEnv *, jobject, jstring, jstring, jstring, jbyte);

/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    StopSmartConnection
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_StopSmartConnection
  (JNIEnv *, jobject);

/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    InitControlServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_InitControlServer
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    QueryClientInfo
 * Signature: (I)[Lmediatek/android/IoTManager/ClientInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_QueryClientInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    CtrlClientOffline
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_CtrlClientOffline
  (JNIEnv *, jobject, jint);

/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    SetGPIO
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_SetGPIO
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    GetGPIO
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_GetGPIO
  (JNIEnv *, jobject, jint);

/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    SetUARTData
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_SetUARTData
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    GetUARTData
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_GetUARTData
  (JNIEnv *, jobject, jint);

/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    SetPWM
 * Signature: (ISSS)I
 */
JNIEXPORT jint JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_SetPWM
  (JNIEnv *, jobject, jint, jshort, jshort, jshort);

/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    GetPWM
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_GetPWM
  (JNIEnv *, jobject, jint);

/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    SetCtrlPassword
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_SetCtrlPassword
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    AddFriend
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_AddFriend
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    InitCtrlPassword
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_InitCtrlPassword
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mediatek_android_IoTManager_IoTManagerNative
 * Method:    SetDataEncrypt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mediatek_android_IoTManager_IoTManagerNative_SetDataEncrypt
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
